export const data = [
  {
    id: 1,
    name: 'nagendra234',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {
        id: 1,
        name: 'what',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern.\n\n The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
      },
      {
        id: 2,
        name: 'why',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes.`,
      },
      {
        id: 3,
        name: 'when',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
      },
      {
        id: 4,
        name: 'where',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
      },
      {
        id: 5,
        name: 'who',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
      },
      {
        id: 6,
        name: 'how',
        content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
      },
    ],
  },
  {
    id: 2,
    name: 'nagendra2',
    title: 'Afghanistan is about to fall to the Taliban',
    content: `The Taliban have continued their rout of Afghan forces, seizing control of Kandahar, Herat and Lashkar Gah in quick succession and moving dangerously close to the capital city of Kabul. The speed of the cities’ collapse, combined with American officials’ announcement that they would evacuate most of the United States Embassy, has deepened the sense of panic across the country. President Joe Biden is keeping a low profile as the world prepares to pay the price of his administration’s premature withdrawal. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 3,
    name: 'nagendra2',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {
        id: 4,
        name: 'where',
        content:
          'some where Pariatur ad deserunt est dolore. Ut aliquip culpa deserunt in elit sunt mollit. Officia cupidatat excepteur est sunt. Reprehenderit ex qui veniam pariatur exercitation do sit veniam ut nisi commodo ullamco dolore.Lorem in ad commodo qui deserunt ipsum id. Ex eiusmod occaecat nostrud sit dolor nulla exercitation amet culpa laboris. Deserunt cupidatat veniam qui eiusmod ea et. Minim aliquip velit nostrud eu dolore nulla incididunt nisi elit incididunt ipsum ipsum. Occaecat exercitation cillum tempor irure culpa incididunt ad cupidatat velit nisi exercitation. Ex excepteur ullamco eu proident quis velit ut officia amet deserunt minim quis cillum pariatur.',
      },
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 4,
    name: 'nagendra2sss34',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 5,
    name: 'nagendra2fefefe34',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 6,
    name: 'nagendra23tjyj4',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 7,
    name: 'nagendra2yjyjn34',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 8,
    name: 'nagendratrr234',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
  {
    id: 9,
    name: 'nagendra2rthth34',
    title: 'Thank you Tokyo',
    content: `COVID-19 has torn a particularly lethal path through diabetics across the world, especially in India and the United States. People with diabetes account for a staggering 40% of those who have died from COVID-19 in the US, and the numbers from India too indicate a similar pattern. The greater concern now is that many patients who have recovered from COVID-19 have developed newly diagnosed, full-blown diabetes. `,
    detail: [
      {id: 1, name: 'what', content: 'some what'},
      {id: 2, name: 'why', content: 'some why'},
      {id: 3, name: 'when', content: 'some when'},
      {id: 4, name: 'where', content: 'some where'},
      {id: 5, name: 'who', content: 'some who'},
      {id: 6, name: 'how', content: 'some how'},
    ],
  },
];
